### ISSUE TITLE
Route old-site urls

### ISSUE THREAD

**Issue by nmaier** [downthemall/website#32] opened 2013-04-07 21:14 UTC
Route some old-site urls to new-site urls (perm-redirect preferred)
- Everything in the old main nav as it still applies, in particular donate, features, contacts
- Old release note pages for 2.0.x and 3.0x as they become available in the KB

**Comment by stefanoverna** [comment] 2013-04-13 14:50
Duplicate of #18

**Closed as completed by stefanoverna** 2013-04-13 14:50 UTC
